name: Cypress

on:
  pull_request:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

  cypress-tests:
    runs-on: ubuntu-latest
    needs: build

    env:
      PORT: 5173

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check if port is available
        run: |
          while ! nc -z localhost $PORT; do
            echo "Port $PORT is in use, trying next port"
            PORT=$((PORT + 1))
          done
          echo "Using port $PORT"

      - name: Start server
        run: npm run dev --port $PORT

      - name: Run Cypress tests
        run: npx cypress run

  deploy:
    runs-on: ubuntu-latest
    needs: [build, cypress-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'