name: Cypress tests PR

on:
  pull_request:
    branches:
      - main

jobs:
  tests: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
      
      - name: Start
        start: npm run dev

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: http://127.0.0.1:5174
          start: npx vite --host
          browser: chrome